### ISSUE TITLE
Negative price of products

### ISSUE THREAD

**Issue by VRVG1** [Pedro-Nicolas-Rios-Vargas/Abarrotes-Valdivia-WEB#1]
Validate that price of products is positive, otherwise in the view Venta producto will calculate wrong the total, cost, and change.
![image](https://user-images.githubusercontent.com/64117404/135184201-72e8f384-09e3-438e-893e-b8de4c0b79f5.png)
@Pedro-Nicolas-Rios-Vargas 
@VRVG1

**Comment by Pedro-Nicolas-Rios-Vargas** [comment]
Este issue ya fue solucionado en el commit  20b38
